### ISSUE TITLE
The details are unclear to reproduce the results and the reported performances of VoTr are not convincing

### ISSUE THREAD

**Issue by auniquesun** [PointsCoder/VOTR#21]
After reading the paper twice, I am still confused with the model details, especially the Voxel Transformer Modole (by the way, I am knowledgeable about Transformer) 

For example, 
i) how to connect different VoTr building blocks?
ii) why positional encoding like this, (p_i - p_j)W_pos, then add to K_j, V_j, without Q_j? In original Transformer, firstly, the token embedding adds position embedding, then convert to Q, K, V with different linear projections.
iii) why is it necessary extract features on empty voxels and in ablation studies, there is no relevant evidence.
iiii) the highest score in KITTI 3D object detection benchmark is ~85%, while VoTr achevies 89+\%
v) ...

Besides, the 'scripts' folder described in the Readme is absent.

**Comment by PointsCoder** [comment]
@auniquesun 
1) Just feed the output voxels and features of the preceding block into the next block.
2) VoTr is NOT like vanilla Transformer. Adding positional embedding to KV yields better performance. See the paper for the detailed formulas.
3) Because we need voxel downsampling to maintain high efficiency, and as shown in the supp. material, voxel downsampling generates larger voxels at the EMPTY space, which brings the need of extracting features for empty voxels.
4) You made a mistake on the evaluation metric. On the KITTI website, the AP of the mod. classes are compared (as you said ~85%). In the paper, the APs of all difficulties are reported, easy 89.90, mod. 82.09, hard 79.14. See Table 2.

It seems that you didn't really read the paper carefully. I hope that you can read it again before you have further questions.

**Comment by CARASO** [comment]
the 'scripts' folder described in the Readme is absent.
